INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('AD', 'Andorra');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('AE', 'Emiratos Árabes Unidos');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('AF', 'Afganistn');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('AG', 'Antigua y Barbuda');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('AI', 'Anguilla');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('AL', 'Albania');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('AM', 'Armenia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('AN', 'Antillas Holandesas');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('AO', 'Angola');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('AQ', 'Antártida');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('AR', 'Argentina');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('AS', 'Samoa Americana');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('AT', 'Austria');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('AU', 'Australia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('AW', 'Aruba');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('AZ', 'Azerbaiján');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('BA', 'Bosnia y Herzegovina');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('BB', 'Barbados');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('BD', 'Bangladesh');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('BE', 'Bélgica');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('BF', 'Burkina Faso');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('BG', 'Bulgaria');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('BH', 'Bahrein');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('BI', 'Burundi');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('BJ', 'Benín');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('BM', 'Islas Bermudas');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('BN', 'Sultanato de Brunei');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('BO', 'Bolivia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('BR', 'Brasil');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('BS', 'Islas Bahamas');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('BT', 'Bhután');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('BV', 'Isla Bouvet');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('BW', 'Botswana');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('BY', 'Bielorusia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('BZ', 'Belice');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('CA', 'Canadá');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('CC', 'Islas Cocos (Keeling)');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('CD', 'Rep. Dem. del Congo (Zaire)');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('CF', 'República Centro - Africana');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('CG', 'Congo');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('CH', 'Suiza');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('CI', 'Costade Marfil');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('CK', 'Islas Cook');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('CL', 'Chile');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('CM', 'Camerún');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('CN', 'China');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('CO', 'Colombia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('CR', 'Costa Rica');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('CU', 'Cuba');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('CV', 'Cabo Verde');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('CX', 'Isla Christmas');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('CY', 'Chipre');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('CZ', 'República Checa');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('DE', 'Alemania');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('DJ', 'Djibouti');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('DK', 'Dinamarca');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('DM', 'Dominica');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('DO', 'República Dominicana');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('DZ', 'Algeria');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('EC', 'Ecuador');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('EE', 'Estonia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('EG', 'Egipto');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('EH', 'Sahara Occidental');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('ER', 'Eritrea');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('ES', 'España');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('ET', 'Etiopía');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('FI', 'Finlandia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('FJ', 'Fidji');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('FK', 'Islas Malvinas (Islas Falkland)');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('FM', 'Estados Federados de Micronesia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('FO', 'Islas Féroe');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('FR', 'Francia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('GA', 'Gabón');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('GB', 'Reino Unido');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('GD', 'Granada');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('GE', 'Georgia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('GF', 'Guayana Francesa');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('GH', 'Ghana');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('GI', 'Gibraltar');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('GL', 'Groenlandia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('GM', 'Gambia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('GN', 'Guinea');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('GP', 'Guadaloupe');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('GQ', 'Guinea Ecuatorial');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('GR', 'Grecia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('GS', 'Islas Georgia y Sandwich del Sur');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('GT', 'Guatemala');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('GU', 'Guam');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('GW', 'Guinea - Bissau');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('GY', 'Guayana');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('HK', 'Hong Kong');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('HM', 'Islas Heard e Islas Mcdonald');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('HN', 'Honduras');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('HR', 'Croacia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('HT', 'Haití');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('HU', 'Hungría');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('ID', 'Indonesia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('IE', 'Irlanda');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('IL', 'Israel');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('IN', 'India');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('IO', 'Terr. Británico del Océano Índico');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('IQ', 'Irak');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('IR', 'República Islámica de Irán');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('IS', 'Iselandia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('IT', 'Italia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('JM', 'Jamaica');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('JO', 'Jordania');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('JP', 'Japón');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('KE', 'Kenia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('KG', 'Kirgizstán');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('KH', 'Camboya');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('KI', 'Kiribati');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('KM', 'Islas Comores');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('KN', 'San Kittsy Nevis');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('KP', 'República Democrática de Corea');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('KR', 'República de Corea');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('KW', 'Kuwait');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('KY', 'Islas Cayman');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('KZ', 'Kazajistán');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('LA', 'Repblica Demo. Popular de Laos');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('LB', 'Líbano');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('LC', 'Santa Lucía');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('LI', 'Liechtenstein');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('LK', 'SriLanka');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('LR', 'Liberia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('LS', 'Lesotho');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('LT', 'Lituania');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('LU', 'Luxemburgo');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('LV', 'Letonia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('LY', 'Libia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('MA', 'Marruecos');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('MC', 'Mónaco');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('MD', 'República de Moldova');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('MG', 'Madagascar');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('MH', 'Islas Marshall');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('MK', 'Ant. Rep. Yugoslava de Macedonia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('ML', 'Mali');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('MM', 'Myanmar');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('MN', 'Mongolia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('MO', 'Macao');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('MP', 'Islas Marianas del Norte');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('MQ', 'Martinica');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('MR', 'Mauritania');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('MS', 'Montserrat');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('MT', 'Malta');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('MU', 'Mauricio');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('MV', 'Islas Maldivas');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('MW', 'Malawi');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('MX', 'México');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('MY', 'Malasia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('MZ', 'Mozambique');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('NA', 'Namibia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('NC', 'Nueva Caledonia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('NE', 'Niger');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('NF', 'Isla Norfolk');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('NG', 'Nigeria');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('NI', 'Nicaragua');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('NL', 'Holanda');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('NO', 'Noruega');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('NP', 'Nepal');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('NR', 'Nauru');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('NU', 'Niue');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('NZ', 'Nueva Zelanda');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('OM', 'Omán');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('PA', 'Panamá');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('PE', 'Perú');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('PF', 'Polinesia Francesa');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('PG', 'Papua - Nueva Guinea');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('PH', 'Filipinas');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('PK', 'Pakistán');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('PL', 'Polonia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('PM', 'San Pierre y Miquelon');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('PN', 'Isla Pitcairn');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('PR', 'Puerto Rico');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('PS', 'Territorio Ocupado de Palestina');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('PT', 'Portugal');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('PW', 'Islas Palau');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('PY', 'Paraguay');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('QA', 'Qatar');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('RE', 'Isla Reunión');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('RO', 'Rumanía');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('RU', 'Federación Rusa');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('RW', 'Ruanda');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('SA', 'Arabia Saud');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('SB', 'Islas Salomón');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('SC', 'Seychelles');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('SD', 'Sudán');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('SE', 'Suecia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('SG', 'Singapur');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('SH', 'Santa Helena');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('SI', 'Eslovenia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('SJ', 'Svalbard y Jan Mayen');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('SK', 'Eslovaquia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('SL', 'Sierra Leona');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('SM', 'San Marino');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('SN', 'Senegal');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('SO', 'Somalía');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('SR', 'Surinám');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('ST', 'Sao Tomú y Príncipe');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('SV', 'El Salvador');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('SY', 'República Árabe Siria');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('SZ', 'Swazilandia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('TC', 'Islas Turcos y Caicos');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('TD', 'Chad');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('TF', 'Territorios Franceses del Sur');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('TG', 'Togo');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('TH', 'Thailandia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('TJ', 'Tadjikistán');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('TK', 'Toquelau');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('TM', 'Turkmenistán');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('TN', 'Tunez');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('TO', 'Tonga');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('TP', 'Timor Oriental');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('TR', 'Turquía');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('TT', 'Trinidad y Tobago');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('TV', 'Tuvalu');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('TW', 'Taiwan');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('TZ', 'República Unida de Tanzania');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('UA', 'Ukraina');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('UG', 'Uganda');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('UM', 'Islas Menores Exteriores EEUU');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('US', 'EEUU');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('UY', 'Uruguay');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('UZ', 'Uzbekistán');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('VA', 'Santa Sede (Vaticano)');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('VC', 'San Vincente Y Las Granadinas');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('VE', 'Venezuela');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('VG', 'Islas Vírgenes Británicas');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('VI', 'Islas Vírgenes de Eeuu');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('VN', 'Vietnám');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('VU', 'Vanuatu');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('WF', 'Wallis Y Futuna');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('WS', 'Samoa');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('YE', 'Yemen');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('YT', 'Mayotte');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('YU', 'Yugoslavia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('ZA', 'Suráfrica');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('ZM', 'Zambia');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('ZR', 'Zaire');
INSERT INTO paises (CODIGO_PAIS,PAIS) VALUES ('ZW', 'Zimbabue');
